-- full discriptionof table book
SELECT FROM COLUMN_NAME, COLUMN_TYPE, IS_NULLABLE, COLUMN_KEY, COLUMN_DEFAULT, EXTRA
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA ='alx_Book_store'
  AND TABLE_NAME = 'Book';